<div id="mainBody">

    <div class="mainPanel">

        <div id="content" class="mainContent">

            <h1 class="title_event" style="font-size:25px">Learn More About ConcertQ.com</h1>
            <div class="pagesContainer">

                <div class="pagesContent">
                    <div class="copyArticle">
                        <br><br>

                        <div class="imageContainer right">
                            <img src="<?php echo $this->basePath(); ?>/img/about.jpg"><br><br>
                            
                        </div>
                        <h1 style="font-size:16px">About Us</h1>
                        <p>When you have enthusiasm for music and entertainment, you certainly love attending live concerts and enjoy fully. But what’s disappointing in some cases is the lack of finding tickets or just the prices are incredibly high. Now you have a place where to get what you need and avoid any frustrations related to lack of tickets. </p><br>

                        <h1 style="font-size:16px">What We Do</h1>

                        <p>ConcertQ provides tickets for hot concerts appearing around the country at reasonable prices. It’s up to you now to choose which concert you are interested in and book your tickets. We list cheap concert tickets for almost all hot performers. And when a great concert is being held somewhere in your city, you can come here and reserve a seat and be part of the joyful moments. </p><br>

                        <p>Now you have no excuse of missing any events as the tickets are most of the time available at reasonable prices, and when you book a bit early you’ll be luckier to save more money and get the best seats. ConcertQ takes you to the heart of entertainment where you can join hundreds of fans which whom you share love for the performer.</p><br>

                        <p>Even in those cases when someone might tell you that it’s too late to get a ticket, you still can check our website and maybe get one, or contact us and see if there’s something we can do to help. The uniqueness of ConcertQ is the ability to secure tickets for hottest events and still keep the prices at a reasonable rate.</p><br>

                        <p>We have built a great experience in selling tickets for hot concerts and big festivals, and hundreds of fans have already made ConcertQ their primary store to get cheap tickets. Our hard work is not seasonal, but we do our best all along the year to secure seats for fans that relate on us to get their tickets.</p><br>

                    </div>
                </div>
                <div class="pagesNav">
                    <div class="inner">
                        <a href="<?php echo $this->url('www/about', array()); ?>" alt="Read About ConcertQ.com" title="Read About ConcertQ.com" >About Us</a>

                        <a alt="ContactQ.com" title="Contact ConcertQ.com" href="<?php echo $this->url('www/contact', array()); ?>">Contact Us</a>

                        <a href="<?php echo $this->url('www/help', array()); ?>" alt="Read the ConcertQ.com Help" title="Read the ConcertQ.com Help" class="last ">Help</a>

                    </div>
                    <div class="inner">
                          <a href="https://www.facebook.com/concertticketsq" alt="Follow us on Facebook" title="Follow us on Facebook">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-facebook.png"></span></a>

                         <a href="https://twitter.com/Concert_Q" alt="Follow us on Twitter" title="Follow us on Twitter">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-twitter.png"></span></a>

                        <a href="https://plus.google.com/110116933600242198559" alt="Follow us on Google plus" title="Follow us on Google plus">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-googleplus.png"></span></a>

                        <a href="http://www.pinterest.com/concertq/" alt="Follow us on Pinterest" title="Follow us on Pinterest">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-pinterest.png"></span></a>

                    </div>
                    <div class="inner-facebook">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fconcertticketsq&amp;width&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false&amp;appId=517712165003999" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:290px;width:200px" allowTransparency="true"></iframe>
                    </div>


                </div>
                
                <div class="clear"></div>
            </div>

            <div class="clear"></div>
        </div>
    </div>
    <!--<div align="left" class="ticketsanaheim_box_cit_bot-page">
       

        <div class="footer-container">

            <div class="foot">

                <div class="foot_link">
                    <a href="http://www.ticketsanaheim.org/aboutus.php" style="text-decoration:none;" title="About Us">About Us</a> | <a href="http://www.ticketsanaheim.org/contact.php" style="text-decoration: none;" title="Contact Us">Contact Us</a> | <a href="http://www.ticketsanaheim.org/help.php" style="text-decoration: none;" title="Help">Help</a> <br>
                    <h4> Concert Tickets Q</h4>
                    Copyright &copy; 2014. concerticketsq.com.
                    All Rights Reserved.

                </div>
                <div class="foot_social">
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-facebook.png" class="img_facebook" title="facebook"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-twitter.png" class="img_facebook" title="twitter"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-googleplus.png" class="img_facebook" title="googleplus"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-pinterest.png" class="img_facebook" title="pinterest"></a>
                </div>
            </div>
        </div>

    </div>-->
</div>